enter_accept = true

[stats]
common_subcommands = [
  'apt',
  'cargo',
  'dnf',
  'docker',
  'git',
  'go',
  'ip',
  'kubectl',
  'npm',
  'pnpm',
  'podman',
  'systemctl',
  'tmux',
  'yarn',
]

# Set sync_address in environment to allow overriding via $DOTFILES_LOCAL.
